name: "lotofacil"
version: "1.0.0"
config-version: 2

profile: "lotofacil"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lotofacil:
    +persist_docs:
      relation: true
      columns: true
    bronze:
      +materialized: table
      +schema: bronze
      +tags: ["bronze"]
    silver:
      +materialized: table
      +schema: silver
      +tags: ["silver"]

seeds:
  lotofacil:
    +schema: bronze
    +persist_docs:
      relation: true
      columns: true
    +tags: ["bronze", "dictionary"]
    ball_names:
      +post-hook:
        - "alter table {{ this }} drop constraint if exists {{ this.identifier }}_pkey"
        - "alter table {{ this }} add primary key (number)"
    ball_orders:
      +post-hook:
        - "alter table {{ this }} drop constraint if exists {{ this.identifier }}_pkey"
        - "alter table {{ this }} add primary key (draw_order)"
